apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    run: flask
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    name: http
    protocol: TCP
  selector:
    run: flask
