apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq
spec:
  selector:
    matchLabels:
      run: rmq
  template:
    metadata:
      labels:
        run: rmq
    spec:
      containers:
      - name: simple-rmq
        image: cheechundocker/new_rmq:latest 
        ports:
        - containerPort: 5672
